In [1]:
import numpy as np

#### Initialization of matrices and inner product

In [2]:
a = np.array([[9, 3, 5], [4, 1, 2]])
print a.shape

(2, 3)


In [3]:
b = np.array([[1, 3, 2], [2, -5, 3]]).T
print b.shape

(3, 2)


In [4]:
c = np.dot(a, b)
print c

[[28 18]
 [11  9]]


#### Outer product step by step

In [5]:
c0 = np.dot(a[:, 0].reshape(-1, 1), b[0, :].reshape(1, -1))
print c0

[[ 9 18]
 [ 4  8]]


In [6]:
c1 = np.dot(a[:, 1].reshape(-1, 1), b[1, :].reshape(1, -1))
c2 = np.dot(a[:, 2].reshape(-1, 1), b[2, :].reshape(1, -1))

print c1
print c2

[[  9 -15]
 [  3  -5]]
[[10 15]
 [ 4  6]]


In [7]:
c_sum = c0 + c1 + c2
print c_sum
print (c_sum == c).all()

[[28 18]
 [11  9]]
True


#### Outer product with a function

In [8]:
# element-wise product of a column and a row
ew_prod = lambda col,row: np.dot(col.reshape(-1, 1), row.reshape(1, -1))

# outer product, map and reduce
op = lambda x,y: reduce(
                        lambda l,r: l+r, 
                           map(
                           lambda i: ew_prod(x[:, i], y[i, :]), 
                               range(x.shape[1])
                           )
                       )

In [9]:
c_op = op(a, b)
print c_op
print (c_op == c).all()

[[28 18]
 [11  9]]
True


#### Test on a larger matrix

In [10]:
x = np.random.randint(0, 1000, size=(1000, 5))

In [11]:
c = np.dot(x.T, x)
c_op = op(x.T, x)
print (c_op == c).all()

True
